name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: itsKayWat
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=C2FFC7&color_dots=#000000,#CB9DF0,#C2FFC7,#ffffff

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Generate Snake'
